[functions.send-auth-email]
verify_jwt = false

[functions.sms-appointment-notify]
verify_jwt = false

[functions.sms-reminder]
verify_jwt = false

[functions.sms-send-otp]
verify_jwt = false

[functions.sms-thank-you]
verify_jwt = false

[functions.sms-verify-otp]
verify_jwt = false
